// This file is generated by scripts/generate-beep-table.cjs
// Do not edit manually. Update Testdata/Beeptest.csv and re-run the script.

export type BeepTableRow = { decimal: number; niveau: string; kondital: number };
export const BEEP_TABLE: BeepTableRow[] = [
  {
    "decimal": 5.111111111,
    "niveau": "05,01",
    "kondital": 27.2822321
  },
  {
    "decimal": 5.222222222,
    "niveau": "05,02",
    "kondital": 27.64147284
  },
  {
    "decimal": 5.333333333,
    "niveau": "05,03",
    "kondital": 28.00122222
  },
  {
    "decimal": 5.444444444,
    "niveau": "05,04",
    "kondital": 28.36148025
  },
  {
    "decimal": 5.555555556,
    "niveau": "05,05",
    "kondital": 28.72224691
  },
  {
    "decimal": 5.666666667,
    "niveau": "05,06",
    "kondital": 29.08352222
  },
  {
    "decimal": 5.777777778,
    "niveau": "05,07",
    "kondital": 29.44530617
  },
  {
    "decimal": 5.888888889,
    "niveau": "05,08",
    "kondital": 29.80759877
  },
  {
    "decimal": 6,
    "niveau": "05,09",
    "kondital": 30.1704
  },
  {
    "decimal": 6.111111111,
    "niveau": "06,01",
    "kondital": 30.53370988
  },
  {
    "decimal": 6.222222222,
    "niveau": "06,02",
    "kondital": 30.8975284
  },
  {
    "decimal": 6.333333333,
    "niveau": "06,03",
    "kondital": 31.26185556
  },
  {
    "decimal": 6.444444444,
    "niveau": "06,04",
    "kondital": 31.62669136
  },
  {
    "decimal": 6.555555556,
    "niveau": "06,05",
    "kondital": 31.9920358
  },
  {
    "decimal": 6.666666667,
    "niveau": "06,06",
    "kondital": 32.35788889
  },
  {
    "decimal": 6.777777778,
    "niveau": "06,07",
    "kondital": 32.72425062
  },
  {
    "decimal": 6.888888889,
    "niveau": "06,08",
    "kondital": 33.09112099
  },
  {
    "decimal": 7,
    "niveau": "06,09",
    "kondital": 33.4585
  },
  {
    "decimal": 7.1,
    "niveau": "07,01",
    "kondital": 33.789576
  },
  {
    "decimal": 7.2,
    "niveau": "07,02",
    "kondital": 34.121064
  },
  {
    "decimal": 7.3,
    "niveau": "07,03",
    "kondital": 34.452964
  },
  {
    "decimal": 7.4,
    "niveau": "07,04",
    "kondital": 34.785276
  },
  {
    "decimal": 7.5,
    "niveau": "07,05",
    "kondital": 35.118
  },
  {
    "decimal": 7.6,
    "niveau": "07,06",
    "kondital": 35.451136
  },
  {
    "decimal": 7.7,
    "niveau": "07,07",
    "kondital": 35.784684
  },
  {
    "decimal": 7.8,
    "niveau": "07,08",
    "kondital": 36.118644
  },
  {
    "decimal": 7.9,
    "niveau": "07,09",
    "kondital": 36.453016
  },
  {
    "decimal": 8,
    "niveau": "07,10",
    "kondital": 36.7878
  },
  {
    "decimal": 8.1,
    "niveau": "08,01",
    "kondital": 37.122996
  },
  {
    "decimal": 8.2,
    "niveau": "08,02",
    "kondital": 37.458604
  },
  {
    "decimal": 8.3,
    "niveau": "08,03",
    "kondital": 37.794624
  },
  {
    "decimal": 8.4,
    "niveau": "08,04",
    "kondital": 38.131056
  },
  {
    "decimal": 8.5,
    "niveau": "08,05",
    "kondital": 38.4679
  },
  {
    "decimal": 8.6,
    "niveau": "08,06",
    "kondital": 38.805156
  },
  {
    "decimal": 8.7,
    "niveau": "08,07",
    "kondital": 39.142824
  },
  {
    "decimal": 8.8,
    "niveau": "08,08",
    "kondital": 39.480904
  },
  {
    "decimal": 8.9,
    "niveau": "08,09",
    "kondital": 39.819396
  },
  {
    "decimal": 9,
    "niveau": "08,10",
    "kondital": 40.1583
  },
  {
    "decimal": 9.090909091,
    "niveau": "09,01",
    "kondital": 40.46675207
  },
  {
    "decimal": 9.181818182,
    "niveau": "09,02",
    "kondital": 40.77554463
  },
  {
    "decimal": 9.272727273,
    "niveau": "09,03",
    "kondital": 41.08467769
  },
  {
    "decimal": 9.363636364,
    "niveau": "09,04",
    "kondital": 41.39415124
  },
  {
    "decimal": 9.454545455,
    "niveau": "09,05",
    "kondital": 41.70396529
  },
  {
    "decimal": 9.545454545,
    "niveau": "09,06",
    "kondital": 42.01411983
  },
  {
    "decimal": 9.636363636,
    "niveau": "09,07",
    "kondital": 42.32461488
  },
  {
    "decimal": 9.727272727,
    "niveau": "09,08",
    "kondital": 42.63545041
  },
  {
    "decimal": 9.818181818,
    "niveau": "09,09",
    "kondital": 42.94662645
  },
  {
    "decimal": 9.909090909,
    "niveau": "09,10",
    "kondital": 43.25814298
  },
  {
    "decimal": 10,
    "niveau": "09,11",
    "kondital": 43.57
  },
  {
    "decimal": 10.09090909,
    "niveau": "10,01",
    "kondital": 43.88219752
  },
  {
    "decimal": 10.18181818,
    "niveau": "10,02",
    "kondital": 44.19473554
  },
  {
    "decimal": 10.27272727,
    "niveau": "10,03",
    "kondital": 44.50761405
  },
  {
    "decimal": 10.36363636,
    "niveau": "10,04",
    "kondital": 44.82083306
  },
  {
    "decimal": 10.45454545,
    "niveau": "10,05",
    "kondital": 45.13439256
  },
  {
    "decimal": 10.54545455,
    "niveau": "10,06",
    "kondital": 45.44829256
  },
  {
    "decimal": 10.63636364,
    "niveau": "10,07",
    "kondital": 45.76253306
  },
  {
    "decimal": 10.72727273,
    "niveau": "10,08",
    "kondital": 46.07711405
  },
  {
    "decimal": 10.81818182,
    "niveau": "10,09",
    "kondital": 46.39203554
  },
  {
    "decimal": 10.90909091,
    "niveau": "10,10",
    "kondital": 46.70729752
  },
  {
    "decimal": 11,
    "niveau": "10,11",
    "kondital": 47.0229
  },
  {
    "decimal": 11.09090909,
    "niveau": "11,01",
    "kondital": 47.33884298
  },
  {
    "decimal": 11.18181818,
    "niveau": "11,02",
    "kondital": 47.65512645
  },
  {
    "decimal": 11.27272727,
    "niveau": "11,03",
    "kondital": 47.97175041
  },
  {
    "decimal": 11.36363636,
    "niveau": "11,04",
    "kondital": 48.28871488
  },
  {
    "decimal": 11.45454545,
    "niveau": "11,05",
    "kondital": 48.60601983
  },
  {
    "decimal": 11.54545455,
    "niveau": "11,06",
    "kondital": 48.92366529
  },
  {
    "decimal": 11.63636364,
    "niveau": "11,07",
    "kondital": 49.24165124
  },
  {
    "decimal": 11.72727273,
    "niveau": "11,08",
    "kondital": 49.55997769
  },
  {
    "decimal": 11.81818182,
    "niveau": "11,09",
    "kondital": 49.87864463
  },
  {
    "decimal": 11.90909091,
    "niveau": "11,10",
    "kondital": 50.19765207
  },
  {
    "decimal": 12,
    "niveau": "11,11",
    "kondital": 50.517
  },
  {
    "decimal": 12.08333333,
    "niveau": "12,01",
    "kondital": 50.81003472
  },
  {
    "decimal": 12.16666667,
    "niveau": "12,02",
    "kondital": 51.10335556
  },
  {
    "decimal": 12.25,
    "niveau": "12,03",
    "kondital": 51.3969625
  },
  {
    "decimal": 12.33333333,
    "niveau": "12,04",
    "kondital": 51.69085556
  },
  {
    "decimal": 12.41666667,
    "niveau": "12,05",
    "kondital": 51.98503472
  },
  {
    "decimal": 12.5,
    "niveau": "12,06",
    "kondital": 52.2795
  },
  {
    "decimal": 12.58333333,
    "niveau": "12,07",
    "kondital": 52.57425139
  },
  {
    "decimal": 12.66666667,
    "niveau": "12,08",
    "kondital": 52.86928889
  },
  {
    "decimal": 12.75,
    "niveau": "12,09",
    "kondital": 53.1646125
  },
  {
    "decimal": 12.83333333,
    "niveau": "12,10",
    "kondital": 53.46022222
  },
  {
    "decimal": 12.91666667,
    "niveau": "12,11",
    "kondital": 53.75611806
  },
  {
    "decimal": 13,
    "niveau": "12,12",
    "kondital": 54.0523
  },
  {
    "decimal": 13.08333333,
    "niveau": "13,01",
    "kondital": 54.34876806
  },
  {
    "decimal": 13.16666667,
    "niveau": "13,02",
    "kondital": 54.64552222
  },
  {
    "decimal": 13.25,
    "niveau": "13,03",
    "kondital": 54.9425625
  },
  {
    "decimal": 13.33333333,
    "niveau": "13,04",
    "kondital": 55.23988889
  },
  {
    "decimal": 13.41666667,
    "niveau": "13,05",
    "kondital": 55.53750139
  },
  {
    "decimal": 13.5,
    "niveau": "13,06",
    "kondital": 55.8354
  },
  {
    "decimal": 13.58333333,
    "niveau": "13,07",
    "kondital": 56.13358472
  },
  {
    "decimal": 13.66666667,
    "niveau": "13,08",
    "kondital": 56.43205556
  },
  {
    "decimal": 13.75,
    "niveau": "13,09",
    "kondital": 56.7308125
  },
  {
    "decimal": 13.83333333,
    "niveau": "13,10",
    "kondital": 57.02985556
  },
  {
    "decimal": 13.91666667,
    "niveau": "13,11",
    "kondital": 57.32918472
  },
  {
    "decimal": 14,
    "niveau": "13,12",
    "kondital": 57.6288
  },
  {
    "decimal": 14.07692308,
    "niveau": "14,01",
    "kondital": 57.90562189
  },
  {
    "decimal": 14.15384615,
    "niveau": "14,02",
    "kondital": 58.18268757
  },
  {
    "decimal": 14.23076923,
    "niveau": "14,03",
    "kondital": 58.45999704
  },
  {
    "decimal": 14.30769231,
    "niveau": "14,04",
    "kondital": 58.7375503
  },
  {
    "decimal": 14.38461538,
    "niveau": "14,05",
    "kondital": 59.01534734
  },
  {
    "decimal": 14.46153846,
    "niveau": "14,06",
    "kondital": 59.29338817
  },
  {
    "decimal": 14.53846154,
    "niveau": "14,07",
    "kondital": 59.57167278
  },
  {
    "decimal": 14.61538462,
    "niveau": "14,08",
    "kondital": 59.85020118
  },
  {
    "decimal": 14.69230769,
    "niveau": "14,09",
    "kondital": 60.12897337
  },
  {
    "decimal": 14.76923077,
    "niveau": "14,10",
    "kondital": 60.40798935
  },
  {
    "decimal": 14.84615385,
    "niveau": "14,11",
    "kondital": 60.68724911
  },
  {
    "decimal": 14.92307692,
    "niveau": "14,12",
    "kondital": 60.96675266
  },
  {
    "decimal": 15,
    "niveau": "14,13",
    "kondital": 61.2465
  },
  {
    "decimal": 15.07692308,
    "niveau": "15,01",
    "kondital": 61.52649112
  },
  {
    "decimal": 15.15384615,
    "niveau": "15,02",
    "kondital": 61.80672604
  },
  {
    "decimal": 15.23076923,
    "niveau": "15,03",
    "kondital": 62.08720473
  },
  {
    "decimal": 15.30769231,
    "niveau": "15,04",
    "kondital": 62.36792722
  },
  {
    "decimal": 15.38461538,
    "niveau": "15,05",
    "kondital": 62.64889349
  },
  {
    "decimal": 15.46153846,
    "niveau": "15,06",
    "kondital": 62.93010355
  },
  {
    "decimal": 15.53846154,
    "niveau": "15,07",
    "kondital": 63.2115574
  },
  {
    "decimal": 15.61538462,
    "niveau": "15,08",
    "kondital": 63.49325503
  },
  {
    "decimal": 15.69230769,
    "niveau": "15,09",
    "kondital": 63.77519645
  },
  {
    "decimal": 15.76923077,
    "niveau": "15,10",
    "kondital": 64.05738166
  },
  {
    "decimal": 15.84615385,
    "niveau": "15,11",
    "kondital": 64.33981065
  },
  {
    "decimal": 15.92307692,
    "niveau": "15,12",
    "kondital": 64.62248343
  },
  {
    "decimal": 16,
    "niveau": "15,13",
    "kondital": 64.9054
  },
  {
    "decimal": 16.07692308,
    "niveau": "16,01",
    "kondital": 65.18856036
  },
  {
    "decimal": 16.15384615,
    "niveau": "16,02",
    "kondital": 65.4719645
  },
  {
    "decimal": 16.23076923,
    "niveau": "16,03",
    "kondital": 65.75561243
  },
  {
    "decimal": 16.30769231,
    "niveau": "16,04",
    "kondital": 66.03950414
  },
  {
    "decimal": 16.38461538,
    "niveau": "16,05",
    "kondital": 66.32363964
  },
  {
    "decimal": 16.46153846,
    "niveau": "16,06",
    "kondital": 66.60801893
  },
  {
    "decimal": 16.53846154,
    "niveau": "16,07",
    "kondital": 66.89264201
  },
  {
    "decimal": 16.61538462,
    "niveau": "16,08",
    "kondital": 67.17750888
  },
  {
    "decimal": 16.69230769,
    "niveau": "16,09",
    "kondital": 67.46261953
  },
  {
    "decimal": 16.76923077,
    "niveau": "16,10",
    "kondital": 67.74797396
  },
  {
    "decimal": 16.84615385,
    "niveau": "16,11",
    "kondital": 68.03357219
  },
  {
    "decimal": 16.92307692,
    "niveau": "16,12",
    "kondital": 68.3194142
  },
  {
    "decimal": 17,
    "niveau": "16,13",
    "kondital": 68.6055
  },
  {
    "decimal": 17.07142857,
    "niveau": "17,01",
    "kondital": 68.87136939
  },
  {
    "decimal": 17.14285714,
    "niveau": "17,02",
    "kondital": 69.13744898
  },
  {
    "decimal": 17.21428571,
    "niveau": "17,03",
    "kondital": 69.40373878
  },
  {
    "decimal": 17.28571429,
    "niveau": "17,04",
    "kondital": 69.67023878
  },
  {
    "decimal": 17.35714286,
    "niveau": "17,05",
    "kondital": 69.93694898
  },
  {
    "decimal": 17.42857143,
    "niveau": "17,06",
    "kondital": 70.20386939
  },
  {
    "decimal": 17.5,
    "niveau": "17,07",
    "kondital": 70.471
  },
  {
    "decimal": 17.57142857,
    "niveau": "17,08",
    "kondital": 70.73834082
  },
  {
    "decimal": 17.64285714,
    "niveau": "17,09",
    "kondital": 71.00589184
  },
  {
    "decimal": 17.71428571,
    "niveau": "17,10",
    "kondital": 71.27365306
  },
  {
    "decimal": 17.78571429,
    "niveau": "17,11",
    "kondital": 71.54162449
  },
  {
    "decimal": 17.85714286,
    "niveau": "17,12",
    "kondital": 71.80980612
  },
  {
    "decimal": 17.92857143,
    "niveau": "17,13",
    "kondital": 72.07819796
  },
  {
    "decimal": 18,
    "niveau": "17,14",
    "kondital": 72.3468
  },
  {
    "decimal": 18.07142857,
    "niveau": "18,01",
    "kondital": 72.61561224
  },
  {
    "decimal": 18.14285714,
    "niveau": "18,02",
    "kondital": 72.88463469
  },
  {
    "decimal": 18.21428571,
    "niveau": "18,03",
    "kondital": 73.15386735
  },
  {
    "decimal": 18.28571429,
    "niveau": "18,04",
    "kondital": 73.4233102
  },
  {
    "decimal": 18.35714286,
    "niveau": "18,05",
    "kondital": 73.69296327
  },
  {
    "decimal": 18.42857143,
    "niveau": "18,06",
    "kondital": 73.96282653
  },
  {
    "decimal": 18.5,
    "niveau": "18,07",
    "kondital": 74.2329
  },
  {
    "decimal": 18.57142857,
    "niveau": "18,08",
    "kondital": 74.50318367
  },
  {
    "decimal": 18.64285714,
    "niveau": "18,09",
    "kondital": 74.77367755
  },
  {
    "decimal": 18.71428571,
    "niveau": "18,10",
    "kondital": 75.04438163
  },
  {
    "decimal": 18.78571429,
    "niveau": "18,11",
    "kondital": 75.31529592
  },
  {
    "decimal": 18.85714286,
    "niveau": "18,12",
    "kondital": 75.58642041
  },
  {
    "decimal": 18.92857143,
    "niveau": "18,13",
    "kondital": 75.8577551
  },
  {
    "decimal": 19,
    "niveau": "18,14",
    "kondital": 76.1293
  },
  {
    "decimal": 19.06666667,
    "niveau": "19,01",
    "kondital": 76.38293156
  },
  {
    "decimal": 19.13333333,
    "niveau": "19,02",
    "kondital": 76.63674622
  },
  {
    "decimal": 19.2,
    "niveau": "19,03",
    "kondital": 76.890744
  },
  {
    "decimal": 19.26666667,
    "niveau": "19,04",
    "kondital": 77.14492489
  },
  {
    "decimal": 19.33333333,
    "niveau": "19,05",
    "kondital": 77.39928889
  },
  {
    "decimal": 19.4,
    "niveau": "19,06",
    "kondital": 77.653836
  },
  {
    "decimal": 19.46666667,
    "niveau": "19,07",
    "kondital": 77.90856622
  },
  {
    "decimal": 19.53333333,
    "niveau": "19,08",
    "kondital": 78.16347956
  },
  {
    "decimal": 19.6,
    "niveau": "19,09",
    "kondital": 78.418576
  },
  {
    "decimal": 19.66666667,
    "niveau": "19,10",
    "kondital": 78.67385556
  },
  {
    "decimal": 19.73333333,
    "niveau": "19,11",
    "kondital": 78.92931822
  },
  {
    "decimal": 19.8,
    "niveau": "19,12",
    "kondital": 79.184964
  },
  {
    "decimal": 19.86666667,
    "niveau": "19,13",
    "kondital": 79.44079289
  },
  {
    "decimal": 19.93333333,
    "niveau": "19,14",
    "kondital": 79.69680489
  },
  {
    "decimal": 20,
    "niveau": "19,15",
    "kondital": 79.953
  },
  {
    "decimal": 20.06666667,
    "niveau": "20,01",
    "kondital": 80.20937822
  },
  {
    "decimal": 20.13333333,
    "niveau": "20,02",
    "kondital": 80.46593956
  },
  {
    "decimal": 20.2,
    "niveau": "20,03",
    "kondital": 80.722684
  },
  {
    "decimal": 20.26666667,
    "niveau": "20,04",
    "kondital": 80.97961156
  },
  {
    "decimal": 20.33333333,
    "niveau": "20,05",
    "kondital": 81.23672222
  },
  {
    "decimal": 20.4,
    "niveau": "20,06",
    "kondital": 81.494016
  },
  {
    "decimal": 20.46666667,
    "niveau": "20,07",
    "kondital": 81.75149289
  },
  {
    "decimal": 20.53333333,
    "niveau": "20,08",
    "kondital": 82.00915289
  },
  {
    "decimal": 20.6,
    "niveau": "20,09",
    "kondital": 82.266996
  },
  {
    "decimal": 20.66666667,
    "niveau": "20,10",
    "kondital": 82.52502222
  },
  {
    "decimal": 20.73333333,
    "niveau": "20,11",
    "kondital": 82.78323156
  },
  {
    "decimal": 20.8,
    "niveau": "20,12",
    "kondital": 83.041624
  },
  {
    "decimal": 20.86666667,
    "niveau": "20,13",
    "kondital": 83.30019956
  },
  {
    "decimal": 20.93333333,
    "niveau": "20,14",
    "kondital": 83.55895822
  },
  {
    "decimal": 21,
    "niveau": "20,15",
    "kondital": 83.8179
  },
  {
    "decimal": 21.0625,
    "niveau": "21,01",
    "kondital": 84.06082422
  },
  {
    "decimal": 21.125,
    "niveau": "21,02",
    "kondital": 84.30390938
  },
  {
    "decimal": 21.1875,
    "niveau": "21,03",
    "kondital": 84.54715547
  },
  {
    "decimal": 21.25,
    "niveau": "21,04",
    "kondital": 84.7905625
  },
  {
    "decimal": 21.3125,
    "niveau": "21,05",
    "kondital": 85.03413047
  },
  {
    "decimal": 21.375,
    "niveau": "21,06",
    "kondital": 85.27785938
  },
  {
    "decimal": 21.4375,
    "niveau": "21,07",
    "kondital": 85.52174922
  },
  {
    "decimal": 21.5,
    "niveau": "21,08",
    "kondital": 85.7658
  },
  {
    "decimal": 21.5625,
    "niveau": "21,09",
    "kondital": 86.01001172
  },
  {
    "decimal": 21.625,
    "niveau": "21,10",
    "kondital": 86.25438438
  },
  {
    "decimal": 21.6875,
    "niveau": "21,11",
    "kondital": 86.49891797
  },
  {
    "decimal": 21.75,
    "niveau": "21,12",
    "kondital": 86.7436125
  },
  {
    "decimal": 21.8125,
    "niveau": "21,13",
    "kondital": 86.98846797
  },
  {
    "decimal": 21.875,
    "niveau": "21,14",
    "kondital": 87.23348438
  },
  {
    "decimal": 21.9375,
    "niveau": "21,15",
    "kondital": 87.47866172
  },
  {
    "decimal": 22,
    "niveau": "21,16",
    "kondital": 87.724
  }
] as const;

const BY_NIVEAU = new Map<string, BeepTableRow>(BEEP_TABLE.map((r) => [r.niveau, r]));

export function normalizeNiveau(input: unknown): string | null {
  const raw = String(input ?? "").trim();
  if (!raw) return null;
  const m = raw.match(/^(\d{1,2})\s*[,\.]\s*(\d{1,2})$/);
  if (!m) return null;
  const a = String(Number(m[1])).padStart(2, "0");
  const b = String(Number(m[2])).padStart(2, "0");
  return `${a},${b}`;
}

export function rowByNiveau(niveau: unknown): BeepTableRow | null {
  const n = normalizeNiveau(niveau);
  if (!n) return null;
  return BY_NIVEAU.get(n) ?? null;
}

export function closestRowByDecimal(decimal: number): BeepTableRow | null {
  if (!Number.isFinite(decimal)) return null;
  const arr = BEEP_TABLE;
  if (arr.length === 0) return null;
  let lo = 0, hi = arr.length - 1;
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    const v = arr[mid].decimal;
    if (v === decimal) return arr[mid];
    if (v < decimal) lo = mid + 1; else hi = mid - 1;
  }
  const a = arr[Math.max(0, Math.min(arr.length - 1, hi))];
  const b = arr[Math.max(0, Math.min(arr.length - 1, lo))];
  if (!a) return b ?? null;
  if (!b) return a ?? null;
  return Math.abs(a.decimal - decimal) <= Math.abs(b.decimal - decimal) ? a : b;
}

export function decimalFromResultText(resultText: unknown): number | null {
  const row = rowByNiveau(resultText);
  return row ? row.decimal : null;
}

export function konditalFromResultText(resultText: unknown): number | null {
  const row = rowByNiveau(resultText);
  return row ? row.kondital : null;
}

export const BEEP_BOUNDS = (() => {
  const min = rowByNiveau("08,01");
  const max = rowByNiveau("17,14");
  if (!min || !max) return null;
  return {
    minNiveau: min.niveau,
    maxNiveau: max.niveau,
    minDecimal: min.decimal,
    maxDecimal: max.decimal,
    minKondital: min.kondital,
    maxKondital: max.kondital,
  };
})();
