-- Expand AgeGroup enum values for Sportssys divisions

ALTER TYPE "AgeGroup" ADD VALUE IF NOT EXISTS 'OLDIES';
ALTER TYPE "AgeGroup" ADD VALUE IF NOT EXISTS 'U21';
ALTER TYPE "AgeGroup" ADD VALUE IF NOT EXISTS 'U19';
ALTER TYPE "AgeGroup" ADD VALUE IF NOT EXISTS 'U17';
ALTER TYPE "AgeGroup" ADD VALUE IF NOT EXISTS 'U15';
ALTER TYPE "AgeGroup" ADD VALUE IF NOT EXISTS 'U13';
ALTER TYPE "AgeGroup" ADD VALUE IF NOT EXISTS 'U12';
ALTER TYPE "AgeGroup" ADD VALUE IF NOT EXISTS 'U11';
ALTER TYPE "AgeGroup" ADD VALUE IF NOT EXISTS 'U10';
ALTER TYPE "AgeGroup" ADD VALUE IF NOT EXISTS 'U9';
ALTER TYPE "AgeGroup" ADD VALUE IF NOT EXISTS 'U8';
ALTER TYPE "AgeGroup" ADD VALUE IF NOT EXISTS 'U7';
ALTER TYPE "AgeGroup" ADD VALUE IF NOT EXISTS 'U5';
